-- MySQL Script generated by MySQL Workbench
-- 01/24/17 17:43:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbsistemaLaravel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbsistemaLaravel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbsistemaLaravel` DEFAULT CHARACTER SET utf8 ;
USE `dbsistemaLaravel` ;

-- -----------------------------------------------------
-- Table `dbsistemaLaravel`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistemaLaravel`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(256) NOT NULL,
  `descricao` VARCHAR(256) NULL,
  `condicao` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistemaLaravel`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistemaLaravel`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `idcategoria` INT NOT NULL,
  `codigo` VARCHAR(50) NULL,
  `nome` VARCHAR(100) NOT NULL,
  `estoque` INT NOT NULL,
  `descricao` VARCHAR(512) NULL,
  `imagem` VARCHAR(50) NULL,
  `estado` VARCHAR(20) NULL,
  PRIMARY KEY (`idproduto`),
  INDEX `fk_produto_categoria_idx` (`idcategoria` ASC),
  CONSTRAINT `fk_produto_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `dbsistemaLaravel`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistemaLaravel`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistemaLaravel`.`pessoa` (
  `idpessoas` INT NOT NULL AUTO_INCREMENT,
  `tipo_pessoa` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `tipo_documento` VARCHAR(20) NULL,
  `num_doc` VARCHAR(30) NULL,
  `endereco` VARCHAR(70) NULL,
  `telefone` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idpessoas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistemaLaravel`.`entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistemaLaravel`.`entrada` (
  `identrada` INT NOT NULL AUTO_INCREMENT,
  `idfornecedor` INT NOT NULL,
  `tipo_comprovante` VARCHAR(45) NULL,
  `serie_comprovante` VARCHAR(45) NULL,
  `num_comprovante` VARCHAR(45) NULL,
  `data_hora` DATETIME NOT NULL,
  `taxa` DECIMAL(4,2) NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`identrada`),
  INDEX `fk_entrada_pessoa_idx` (`idfornecedor` ASC),
  CONSTRAINT `fk_entrada_pessoa`
    FOREIGN KEY (`idfornecedor`)
    REFERENCES `dbsistemaLaravel`.`pessoa` (`idpessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistemaLaravel`.`detalhe_entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistemaLaravel`.`detalhe_entrada` (
  `iddetalhe_entrada` INT NOT NULL AUTO_INCREMENT,
  `identrada` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `preco_compra` DECIMAL(9,2) NULL,
  `preco_venda` DECIMAL(9,2) NULL,
  `detalhe_entradacol` VARCHAR(45) NULL,
  PRIMARY KEY (`iddetalhe_entrada`),
  INDEX `fk_detalhe_entrada_idx` (`identrada` ASC),
  INDEX `fk_detalhe_produto_idx` (`idproduto` ASC),
  CONSTRAINT `fk_detalhe_entrada`
    FOREIGN KEY (`identrada`)
    REFERENCES `dbsistemaLaravel`.`entrada` (`identrada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalhe_produto`
    FOREIGN KEY (`idproduto`)
    REFERENCES `dbsistemaLaravel`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistemaLaravel`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistemaLaravel`.`venda` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `tipo_cormprovante` VARCHAR(45) NULL,
  `serie` VARCHAR(45) NULL,
  `num_cormprovante` VARCHAR(45) NULL,
  `data_hora` DATETIME NOT NULL,
  `taxa` DECIMAL(4,2) NULL,
  `total_venda` DECIMAL(9,2) NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvenda`),
  INDEX `fk_venda_cliente_idx` (`idcliente` ASC),
  CONSTRAINT `fk_venda_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `dbsistemaLaravel`.`pessoa` (`idpessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistemaLaravel`.`detalhe_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistemaLaravel`.`detalhe_venda` (
  `iddetalhe_venda` INT NOT NULL AUTO_INCREMENT,
  `idvenda` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `preco_venda` DECIMAL(9,2) NULL,
  `desconto` DECIMAL(9,2) NULL,
  PRIMARY KEY (`iddetalhe_venda`),
  INDEX `fk_detalhe_venda_idx` (`idvenda` ASC),
  INDEX `fk_detalhe_produto_idx` (`idproduto` ASC),
  CONSTRAINT `fk_detalhevenda_venda`
    FOREIGN KEY (`idvenda`)
    REFERENCES `dbsistemaLaravel`.`venda` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalhevenda_produto`
    FOREIGN KEY (`idproduto`)
    REFERENCES `dbsistemaLaravel`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
